version: '3.5'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        uid: 1000
    environment:
      - DB_HOST=db
      - DB_DATABASE=ecommerce
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    ports:
      - 8000:80
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: 'auth'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app

networks:
  app:
    driver: bridge
